### PR TITLE
feat: bring back upstream templates

### PR DESCRIPTION
**Pull request by amrbashir**
This PR extracts some of the needed information for wry template into metadata inside Cargo.toml. A lot of the functionality already existed, I just added a couple metadata fields but now the android template is agnostic.

### CODE REVIEW

**Comment by amrbashir** [comment]
I forgot to mention that I only optimized the android studio project to work for all templates, I didn't check how much our xcode project is different from upstream but I will take a look tomorrow.

**Comment by amrbashir** [comment]
I think this PR is ready now.
@wusyong there was a lot of hardcoded dependencies which I moved them to wry's `Cargo.toml` because `cargo-mobile` already supported reading them from there.
I also pulled the xcode project from upstream which removed some unneeded logic and brought in new one with a bit of improvements, but I kept the changes from this commit https://github.com/tauri-apps/cargo-mobile/commit/facf118147e64a5a436c7b0c3edb199f53be4fa9.

**Comment by wusyong** [comment]
I encountered an error with like this and couldn't find the reason:
```
cargo_mobile::util::cli] exiting with ArchInvalid {
        arch: "Simulator",
    }
error: Arch specified by Xcode was invalid
    "Simulator" isn't a known arch
```
Maybe we should open another PR to update upstream commits first.

**Comment by amrbashir** [comment]
The upstream commits are not that much and generally harmless, the only change that might cause trouble is the `project.yml.hbs` file, everything else should be the same and works fine so we can just focus on that file.

The error your posted suggestes that the simulator has a different arch that isn't accounted for so you might need changes in these one or all of these places:
1. in `src/apple/cli.rs:443`
2. in `src/apple/target.rs:147`

**Comment by wusyong** [comment]
The added `Build Rust Code` in project.yaml doesn't seem correct on M1.
Also note that android studio is also fail to build on M1.

**Pull request closed without merging**
