### PR TITLE
fix: allow '-' and '.' in identifier

### PR DESCRIPTION
**Pull request by ddPn08**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist

- [ ] This PR will resolve #\_\_\_
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/cargo-mobile2/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary
- [ ] It can be built on all targets and pass CI/CD.

### Other information
(Please forgive me for not being very good at English.)

Fixed an issue where domains containing '-' or '.' could not be used in `identifier` of tauri.conf.json.
I apologize if there is a reason for this specification.

### CODE REVIEW

**Comment by amrbashir** [comment]
this should probably be fixed in tauri-cli not here, but what are the errors that you get?

**Comment by ddPn08** [comment]
The contents of the error are as follows.

```
base ❯ cargo tauri ios dev --open
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DomainInvalid { domain: "parakeet-inc.com", cause: NotAsciiAlphanumeric { bad_chars: ['-'] } }', /Users/ddpn08/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-cli-2.0.0-alpha.16/src/mobile/mod.rs:318:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I traced the code from the stack trace and found this repository.
https://github.com/tauri-apps/tauri/blob/dev/tooling/cli/src/mobile/mod.rs#L317
https://github.com/tauri-apps/tauri/blob/dev/tooling/cli/src/mobile/mod.rs#L22-L23

**Comment by amrbashir** [comment]
yeah this should definitely be fixed in tauri cli, not here

**Comment by amrbashir** [comment]
Having `-` and `.` in the domain is not valid for android domains AFAIK and tauri should decide if it wants disallow that or replace these character before passing it to `cargo-mobile2`

**Comment by ddPn08** [comment]
understood. thank you.

**Comment by ddPn08** [comment]
Looking at examples such as Flutter, when using a domain with '-' in it, it seems that '-' is used as is for iOS App ID, and '-' is replaced with '_' for Android. .
Is it possible to handle this?

**Comment by amrbashir** [comment]
That would still need to be implemented in tauri-cli, because there is more other places where the domain is used other than here and doesn't make sense to solve the same issue twice.

**Pull request closed without merging**
