### PR TITLE
Add egui example

### PR DESCRIPTION
**Pull request by zeerooth**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [ ] This PR will resolve #___
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri-mobile/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary
- [ ] It can be built on all targets and pass CI/CD.

### Other information

This is partially a continuation of https://github.com/BrainiumLLC/cargo-mobile/pull/48

This PR introduces a new template based on an egui example found here https://github.com/rust-mobile/rust-android-examples/tree/main/agdk-egui

It works on Android and Linux desktop, I couldn't test it anywhere else

### CODE REVIEW

**Review by wusyong — DISMISSED** [review]
Thanks! Could you sign the sommit so I could merge the PR.

**Comment by zeerooth** [comment]
> Thanks! Could you sign the sommit so I could merge the PR.

No problem, I signed the last commit, is it enough?

**Review by wusyong — APPROVED** [review]

**Comment by wusyong** [comment]
You'll have to sign all commits I believe.

**Comment by zeerooth** [comment]
> You'll have to sign all commits I believe.

Alright, I rewrote history and now it seems like every commit is properly verified. Sorry for all of that

**Comment by QuantumEntangledAndy** [comment]
Just trying your equi example with latest install. Had a few issues, on mac and ios.

First I got this error when doing cargo run on the mac

```rust
error[E0603]: function `main` is private
   --> gen/bin/desktop.rs:3:18
    |
3   |     mobile_equi::main();
    |                  ^^^^ private function
    |
note: the function `main` is defined here
   --> /Users/awk21/Projects/Coding/Rust/mobile_equi/src/lib.rs:160:1
    |
160 | fn main() {
    | ^^^^^^^^^

For more information about this error, try `rustc --explain E0603`.
error: could not compile `mobile-equi` due to previous error
```

Which was solvable by adding `pub` to main

What was more troubling was trying to solve the following on the ios

```log
Undefined symbols for architecture arm64:
  "_start_app", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Building targets in dependency order
note: Run script build phase 'Build Rust Code' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'mobile-equi_iOS' from project 'mobile-equi')
** BUILD FAILED **

error: Failed to build via `xcodebuild`
    command ["xcodebuild"] exited with code 65
```

Not sure where `_start_app` is or how to add that it. Any ideas?

**Pull request merged**
